project:
  type: book
  output-dir: docs

book:
  title: First Passive Acoustic Monitoring Strategic Initiative Workshop Report
  subtitle: La Jolla, California 
  date: March 2024
  downloads: [pdf, docx]
  author:
  - name: Sofie Van Parijs
    email: sofie.vanparijs@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: NEFSC
        address: 166 Water Street, Woods Hole, MA
  - name: Catherine Berchok
    email: catherine.berchok@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: AFSC
        address: 7600 Sand Point Way NE, Seattle, WA
  - name: Jason Gedamke
    email: jason.gedamke@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: S&T
        address:  1315 E West Hwy Silver Spring, MD
  - name: Marla Holt 
    email: marla.holt@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: NWFSC
        address: 	2725 Montlake Boulevard East, Seattle, WA

  chapters:
    - index.qmd
    - content/Acknowledgements.qmd
    - text/AttendeeIntros.qmd
    - text/references.qmd
    - text/PAM-SI-Mtg-Exercises-Climate.qmd
    - text/PAM-SI-Mtg-Exercises-StockAssess.qmd

  site-url: https://sael-swfsc.github.io/PAM-SI-Mtg-March2024/
  repo-url: https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
