project:
  type: book
  output-dir: docs

book:
  title: IRA Passive Acoustic Monitoring Strategic Initiative Workshop Report
  subtitle: La Jolla, California 
  date: March 2024
  downloads: [pdf, docx]
  author:
  - name: Sofie Van Parijs
    email: sofie.vanparijs@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: NEFSC
        address: 166 Water Street, Woods Hole, MA
  - name: Catherine Berchok
    email: catherine.berchok@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: AFSC
        address: 7600 Sand Point Way NE, Seattle, WA
  - name: Jason Gedamke
    email: jason.gedamke@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: S&T
        address:  1315 E West Hwy Silver Spring, MD
  - name: Marla Holt 
    email: marla.holt@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: NWFSC
        address: 	2725 Montlake Boulevard East, Seattle, WA
  - name: Erin Oleson 
    email: erin.oleson@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: PIFSC
        address: 	1845 Wasp Blvd, Honolulu, HI
  - name: Shannon Rankin 
    email: shannon.rankin@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: SWFSC
        address: 8901 La Jolla Shores Dr.
  - name: Melissa Soldevilla 
    email: melissa.soldevilla@noaa.gov
    affiliations:
      - name: NOAA Fisheries
        department: SEFSC
        address: 75 Virginia Beach Drive, Miami, FL 33149
  - name: Carrie Wall Bell
    email: carrie.wall@noaa.gov
    affiliations:
      - name: University of Colorado Boulder, Cooperative Institute for Research in Environmental Sciences
        department: NOAA National Centers for Environmental Information
        address: 325 Broadway, Boulder, CO 80305
  - name: Rebecca Van Hoeck
    email: rebecca.vanhoeck@noaa.gov
    affiliations:
      - name: NOO Fisheries 
        department: NEFSC
        address: 166 Water Street, Woods Hole, MA
        
  chapters:
    - index.qmd
    - text/Intro.qmd
  # - text/AttendeeIntros.qmd
    - text/Cloud.qmd
    - text/NCEI.qmd
    - text/Climate.qmd
    - text/StockAssess.qmd
    - text/Soundscape.qmd
    - text/Detection.qmd
    - text/Github.qmd
    - text/Management.qmd
    - text/ListAttendees.qmd
    - text/Acknowledgements.qmd
 #   - text/references.qmd


  site-url: https://sael-swfsc.github.io/PAM-SI-Mtg-March2024/
  repo-url: https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
