project:
  type: book
  output-dir: docs

book:
  title: First Passive Acoustic Monitoring Strategic Initiative Workshop Report
  subtitle: La Jolla, California 
  date: March 2024
  downloads: [pdf, docx]
  author:
  - name: Matti Meikäläinen
    email: matti@jy.fi
    affiliations:
      - name: University of Kemijärvi
        department: Department of Biological and Environmental Science
        address: Kylmäniementie 79, 98120, KEMIJÄRVI, Finland
  - name: Ashok Kumar
    email: akumar@uminn.edu
    affiliations:
      - name: University of Minnesota
        department: Department of Mathematics
        address: 4444 Minneo Drive, Minneapolis, MN

  chapters:
    - index.qmd
    - content/AttendeeIntros.qmd
    - content/Background.qmd
    - content/references.qmd

  site-url: https://sael-swfsc.github.io/PAM-SI-Mtg-March2024
  repo-url: https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - content/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
