# Acknowledgements

The PAM SI working group acknowledges the support from the Inflation Reduction Act and NOAA's Climate Ready Fisheries invesments for supporting the Essential Data Acquisition component that the PAM Strategic Initiative is a part of.

Thank you to NOAA Fisheries Office of the Chief Information Officer for their support of the cloud computing projects and to Jeffrey Walker for his work on the PACM cloud transition. Thank you to the UxS Strategic Initiative for their collaboration on the Pacific Glider projects.

Funding for participation of Taiki Sakai was provided by Bureau of Ocean Energy Management (G14 M20PG00013).

### Workshop attendees:

Ann Allen (NOAA Federal); ann.allen\@noaa.gov

Yvonne Barkley (NOAA Affiliate); yvonne.barkley\@noaa.gov

Carrie Wall Bell (NOAA Affiliate); carrie.wall\@noaa.gov

Catherine Berchok (NOAA Federal); catherine.berchok\@noaa.gov

Kourtney Burger (NOAA Federal); kourtney.burger\@noaa.gov

Manuel Castellote (NOAA Affiliate); manuel.castellote\@noaa.gov\
Genevieve Davis (NOAA Federal); genevieve.davis\@noaa.gov\
Annamaria DeAngelis (NOAA Federal); annamaria.deangelis\@noaa.gov\
Candice Emmons (NOAA Federal); candice.emmons\@noaa.gov\
Jason Gedamke (NOAA Federal); Jason.Gedamke\@noaa.gov

Samara Haver (NOAA Affiliate); samara.haver\@noaa.gov

Marla Holt (NOAA Federal); marla.holt\@noaa.gov

Cory Hom-Weaver (NOAA Affiliate); cory.hom-weaver\@noaa.gov

Jennifer McCullough (NOAA Federal); jennifer.mccullough\@noaa.gov

Megan McKenna (NOAA Affiliate); megan.mckenna\@noaa.gov

Erin Oleson (NOAA Federal); erin.oleson\@noaa.gov\
Shannon Rankin (NOAA Federal); shannon.rankin\@noaa.gov\
Taiki Sakai (NOAA Affiliate); taiki.sakai\@noaa.gov\
Melissa Soldevilla (NOAA Federal); melissa.soldevilla\@noaa.gov\
Ludovic Tenorio (NOAA Affiliate); ludovic.tenorio\@noaa.gov\
Sofie VanParijs (NOAA Federal); sofie.vanparijs\@noaa.gov

Daniel Woodrich (NOAA Affiliate); daniel.woodrich\@noaa.gov\
\
Funding for participation (Taiki Sakai) provided by Bureau of Ocean Energy Management (G14 M20PG00013).\
\
\
\
\
\
\
