---
title: Soundscape Tools, Metrics, Analyses
---

| Data Type | Additional Questions | Data Availability |
|-----------|----------------------|-------------------|
|           |                      |                   |
|           |                      |                   |
|           |                      |                   |
|           |                      |                   |
|           |                      |                   |

: List of data types needed to expand sound metric research questions

---

---

## Target Outcome

One sentence description of the goal for this project

## Project Team

| Name of Lead                | Name of Lead                |        |
|-----------------------------|-----------------------------|--------|
| Marla                       | Megan                       | Samara |
| Name of Project Team Member | Name of Project Team Member |        |
|                             |                             |        |

## Summary

One paragraph summary of (1) what work will be done, (2) how it fills a research or operational need, and (3) how it supports one or more of the PAM SI Objectives.

## Action Items

1.  **Short Name for Action Item:** Description of Action Item in text with as much detail as needed (but no more than needed!). *Deadline: Month, Year.*

2.  **Short Name for Action Item:** Description of Action Item in text with as much detail as needed (but no more than needed!). *Deadline: Month, Year.*

3.  **Short Name for Action Item:** Description of Action Item in text with as much detail as needed (but no more than needed!). *Deadline: Month, Year.*
