---
title: Soundscape analyses, metrics, and tools
---

# Project 1: Soundscape metric processing and archiving

## Target Outcome

Identify, archive, and process soundscape metrics for priority SI PAM datasets to build capacity and consistency across FMCs.

## Project Team

| Samara Haver       |                  |                   |
|--------------------|------------------|-------------------|
| Megan McKenna      | Marla Holt       | Catherine Berchok |
| Melissa Soldevilla | Carrie Wall Bell | Dan Woodrich      |
| Karli Merkens      | Becca Van Hoeck  |                   |

## Summary

This project will add soundscape metrics for priority SI PAM datasets alongside audio files and other metrics to the NCEI Passive Acoustics archive. The soundscape metrics will be used to develop and demonstrate soundscape interpretation and visualization tools being developed as part of the SI. The datasets will also facilitate comparison of data sampled by multiple recording technologies and projects that are unique to select FMCs. A technical guide for processing and archiving PAM data will also be prepared as part of this project. This project will work with SI cloud computing projects to operationalize soundscape metric processing software in the cloud environment. Streamlining and documenting methods to process and archive soundscape metrics supports PAM SI objectives to advance PAM data analysis and integration approaches, and advance archival cloud capabilities.

## Action Items

1.  **Convene working group:** Establish data processing group, [Google doc folder](https://drive.google.com/drive/folders/1PBQbyajbFgidBvQER1vFL6e_WEQZSLm0?usp=drive_link), regular check-in schedule. *Deadline: March 2024*

2.  **Establish software standards:** Standard software options available for use for use with test NRS dataset results from multiple softwares. *Deadline: May 2024 (MANTA, PyPAM), any other by Sept 2024*

3.  **Identify priority datasets:** In coordination with Carrie Wall Bell and NCEI Archiving group decide on soundscape priority datasets for each FSC and flag in the overall SI priority [dataset table](https://docs.google.com/presentation/d/1TewDhV21FjX2ANAzedxMR5s_q94eciiu-iTafjJRUVM/edit#slide=id.g2c4705a5e9b_0_35). *Deadline: April 2024.*

4.  **Prepare analyses:** For priority soundscape datasets: Prep metadata, Share QA/QC protocol/tools, PassivePack and archive audio data to NCEI. *Deadline: April 2024 - December 2024*

5.  **Create supporting documents:** Develop technical reports and videos on processing, included data, minimum QA/QC in coordination with SoundCoop efforts. *Deadline: March 2024 - December 2024*

6.  **Test in pyPAM:** Coordinate with PAM SI Cloud team to test priority NRS audio data sets flagged with hybrid milli-decade (HMD) analysis in pyPAM. *Deadline: June 2024 (pending pyPAM software development completion)*

7.  **Compare soundscape software options:** Provide soundscape software options available (MANTA, pyPAM, updated Triton toolbox, etc.) with comparison documentation for example datasets (NRS or others if necessary). *Deadline: December 2024*

8.  **Generate Hybrid milli-decade output:** FMCs will conduct HMD processing either locally or through the PAM SI Cloud computing and save to NCEI or internal PAM SI cloud environment. *Deadline: Jan 2025 - March 2025*

9.  **NCEI archive data products:** All HMDs will be processed and sent to NCEI archive for level 2-3 data products. *Deadline: March 2025*

10. **Facilitate more complex soundscape analyses:** All priority soundscape datasets and HMD level 1 products will be cloud archived at NCEI or NODD for use in the Soundscape interpretation and visualization project. *Deadline: March 2025*

11. **Support comparison across platforms:** Comparison of soundscape metric results from simultaneously deployed platforms; develop tools to support this type of comparison (ie. PAMscapes). The data processing groups will establish methods for comparison, ongoing opportunistic evaluation will occur throughout the SI, and results will be added to the GitHub Soundscape Group and reported with example datasets. *Deadline: Dependent on participation*

| Lead                       | Platform 1 | Platform 2 |
|----------------------------|------------|------------|
| Catherine Berchok          | Aurals     | SoundTrap  |
| Melissa Soldevilla         | HARP       | SoundTrap  |
| Marla                      | EAR        | SoundTrap  |
| Jason Gedamke/Samara Haver | Haruphone  | SoundTrap  |

1.  **Support comparison across datasets with known differences:** Develop a format or tool to support comparison of datasets with known differences, such as perfect timing (MARS), dropped time (SoundTrap), duty cycled (AK, NW), frequency-dependent calibration (NRS, HARP), file format (XWAV). *Deadline: Dependent on participation*

# Project 2: Soundscape metric interpretation and visualization

## Target Outcome

Create a set of soundscape metric interpretation open-source processing pathways and visualizations for across FMCs comparisons and FMCs-specific soundscape priorities.

## Project Team

| Samara Haver       | Megan McKenna    |                   |
|--------------------|------------------|-------------------|
| Becca Van Hoeck    | Marla Holt       | Catherine Berchok |
| Melissa Soldevilla | Carrie Wall Bell | Dan Woodrich      |
| Karli Merkens      | Genevieve Davis  | Sofie Van Parijs  |
| Jason Gedamke      |                  |                   |

## Summary

This project will build on existing tools in PAMscapes (R/CRAN) to create and document processing pathways for soundscape metric interpretation. NOAA Noise Reference Station soundscape metrics will be used to build the pathways and evaluate outputs. Additional soundscape metrics from SI priority data sets will be incorporated based on availability from priority project #1 for soundscapes. This priority supports SI objective #2 by creating decision-support tools that are relevant at regional and national scales. It also supports #4 by integrating PAM data with variables to provide context for different soundscapes (environmental data, species-detections, etc).

## Action Items

1.  **Title:** . *Deadline:*

2.  **Title:** . *Deadline:*

3.  **Title:** . *Deadline:*

4.  **Title:** . *Deadline:*

5.  **Title:** . *Deadline:*

6.  **Title:** . *Deadline:*

7.  **Title:** . *Deadline:*

8.  **Title:** . *Deadline:*

9.  **Title:** . *Deadline:*

10. **Title:** . *Deadline:*

11. **Title:** . *Deadline:*

12. **Title:** . *Deadline:*
